#!/usr/bin/env python
# -*- coding: CP936 -*-
#
# generated by wxGlade 0.7.2 on Tue Jun 13 11:04:15 2017
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ManagerFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ManagerFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.mod_list = wx.ListCtrl(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ManagerFrame.__set_properties
        self.SetTitle("Mod Manager")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ManagerFrame.__do_layout
        main_sizer = wx.BoxSizer(wx.VERTICAL)
        main_sizer.Add(self.mod_list, 1, wx.EXPAND, 0)
        self.SetSizer(main_sizer)
        main_sizer.Fit(self)
        self.Layout()
        # end wxGlade

# end of class ManagerFrame
